### ISSUE TITLE
drag-drop of the cards in the browser app is not working

### ISSUE THREAD

**Issue by clovett** [AvaloniaUI/Solitaire#15]
the desktop app works fine, but I cannot drag an ace from the pile to the let where it belongs, drag with mouse does nothing.

**Comment by maxkatz6** [comment]
Can you be a bit more specific about this issue? What game mode is it, what browser+os is it and what input device do you use (mouse or touch...)?

I can drag and drop it in Chrome with mouse.

![image](https://github.com/AvaloniaUI/Solitaire/assets/3163374/cdc7768b-5a94-45a9-a170-2802ae033e24)
![image](https://github.com/AvaloniaUI/Solitaire/assets/3163374/65cac499-135b-42b8-bc44-6bed796d0462)

**Comment by clovett** [comment]
It's using Microsoft Edge Version 120.0.2210.77 (Official build) (64-bit), on Windows.  I also tried Chrome, same thing.  Now it's gotten worse in fact, I can click one card on the stack, and then the mouse seems to stop working entirely.  Cannot reveal another card or drag the new card anywhere.  I tried running the browser DevTools, no exceptions being thrown in the debugger, no debug console output.  I'm selecting "Klondike" game in the main menu.

Now it's not even doing the dealing at all, so I have this:

![image](https://github.com/AvaloniaUI/Solitaire/assets/3336415/4fbca534-fbbf-4698-9dc0-8a399f42be74)

**Comment by maxkatz6** [comment]
I guess you are building it with .NET 8 from the master branch. Can you try with net7?

**Comment by clovett** [comment]
Ah yes, .net7 with the `wasm-tools-net7` works much better.

**Comment by maxkatz6** [comment]
Fixed by replacing runMainAndExit with runMain
